erDiagram
    ITEMS ||--o{ ANALISIS : "utilizado_en"
    ANALISIS ||--o{ PRESUPUESTOS : "incluido_en"
    
    ITEMS {
        string id "MAT-XXXX"
        boolean activo
        string categoria
        string descripcion
        timestamp fecha_actualizacion
        number precio_unitario
        string unidad
    }
    
    ANALISIS {
        string id "ACXX"
        string codigoDisplay "M.MM (Mayor.Menor)"
        number costo_total
        timestamp fecha_actualizacion
        object indice "{ mayor: number, menor: number }"
        object insumos "{ INSXXX: { item_id, cantidad, ... } }"
        string nombre
        number rendimiento
        object rubro "{ id, nombre, unidad }"
        string unidad
    }
    
    PRESUPUESTOS {
        string id "PRESXXXX"
        object datos_generales "{ beneficio_explicito, comitente, ... }"
        object items "{ item_X: { analisis_id, cantidad, ... } }"
        object subtotales "{ STX: { importe, incidencia, nombre } }"
        number total_general
    }
